spring:
  profiles:
    active: local
---
spring:
  profiles: local
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
logging:
  level:
    com:
      purcotton:
        omni:
          ordersync:
            core: debug
---
spring:
  profiles: dev
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.206.205:3306/tradedb?characterEncoding=utf-8&useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: tradeuser
    password: Tradeuser123
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
logging:
  level:
    com:
      purcotton:
        omni:
          ordersync:
            core: info
---
spring:
  profiles: pg
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test01
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
logging:
  level:
    com:
      purcotton:
        omni:
          ordersync:
            core: info